import { useCallback, useEffect, useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";

import axios from "axios";
import { useDropzone } from "react-dropzone";

import styles from "../styles/Home.module.css";
import {
  Button,
  CopyButton,
  Heading,
  HomeButton,
  ImageContainer,
  InnerUploadBox,
  LinkContainer,
  LinkText,
  Modal,
  Progress,
  StyledImage,
  Text,
  UploadBox,
} from "../components/StyledComponents";

const LARGE = "large";


export default function Home() {
  const [uploadedImage, setuploadedImage] = useState({});
  const [isImageShowing, setIsImageShowing] = useState(false);
  const [wait, setWait] = useState(false);
  const [progress, setProgress] = useState({
    loaded: 0,
    total: 0,
  });
  const loadingModalRef = useRef(null);

  const onDrop = useCallback((acceptedFiles) => {
    uploadToServer(acceptedFiles[0]);
  }, []);

  const { getRootProps, getInputProps, isDragActive, open } = useDropzone({
    onDrop,
    accept: {
      "image/*": [".jpeg", ".jpg", ".png"],
    },
    noClick: true,
  });

  const uploadToServer = async (image) => {
    // @ts-ignore
    loadingModalRef.current.showModal();
    const body = new FormData();
    body.append("data", JSON.stringify({}));
    body.append("files.image", image);
    const response = await axios.post(
      `https://strapi-image-uploader-backend.herokuapp.com/api/image-uploaders?populate=image`,
      body,
      {
        onUploadProgress: (progressEvent) => {
          const { loaded, total } = progressEvent;
          if (loaded === total) {
            setWait(true);
          }
          setProgress({
            loaded: loaded,
            total: total,
          });
        },
      }
    );
    const { data } = await response;
    await setuploadedImage(data.data.attributes.image.data.attributes);
    // @ts-ignore
    loadingModalRef.current.close();
    setIsImageShowing(true);
    setWait(false);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(uploadedImage[LARGE].url).then(() => {
      alert(`Coppied ${uploadedImage[LARGE].url} to clipboard`);
    });
  };

  console.log(uploadedImage)


  if (isImageShowing && uploadedImage[LARGE].hasOwnProperty("url")) {
    return (
      <>
        <Head>
          <title>My Image</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href={uploadedImage[LARGE].url} />
        </Head>
        <ImageContainer>
          <StyledImage
            src={uploadedImage[LARGE].url}
            height={uploadedImage[LARGE].height}
            width={uploadedImage[LARGE].width}
            alt="uploadedImage"
          />
          <LinkContainer>
            <LinkText>{`${uploadedImage[LARGE].url}`}</LinkText>
            <CopyButton onClick={copyToClipboard}>Copy</CopyButton>
          </LinkContainer>
          <HomeButton onClick={() => setIsImageShowing(false)}>
            Go to Home
          </HomeButton>
        </ImageContainer>
      </>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Image Uploader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <UploadBox {...getRootProps()}>
          <InnerUploadBox>
            <Heading>Upload your images here</Heading>
            <Image
              src="/undraw_upload_re_pasx.svg"
              alt="upload bg pic"
              width={180}
              height={180}
            />
            <div>
              <input id="imageUploader" {...getInputProps()} />
              {isDragActive ? (
                <Text>Drop now ...</Text>
              ) : (
                <Text>Drag & drop your images here</Text>
              )}
            </div>
            <span>OR</span>
            <Button onClick={open}>Choose file</Button>
          </InnerUploadBox>
        </UploadBox>
      </main>
      <Modal ref={loadingModalRef}>
        <Progress max={progress.total} value={progress.loaded}>{`${
          Math.floor(progress.loaded / progress.total) * 100
        }%`}</Progress>
        <Text>{wait ? "Please Wait..." : "Uploading..."}</Text>
      </Modal>
    </div>
  );
}
